# -*- coding: utf-8 -*-
# =============================================================================
# Copyright (C) Les solutions géostack, Inc
#
# This file was produced as part of a research project conducted for
# The World Bank Group and is licensed under the terms of the MIT license.
#
# For inquiries, contact: info@geostack.ca
# Repository: https://github.com/geo-stack/sahel
# =============================================================================

# ---- Standard imports.
from pathlib import Path

# ---- Third party imports.
import numpy as np
import rasterio
from scipy.ndimage import distance_transform_edt

# ---- Local imports.


def dist_to_streams(dem: Path, streams: Path, output: Path):
    """
    Calculate distance to nearest stream and its coordinates for
    each DEM pixel.

    For every pixel in the input DEM, computes the Euclidean distance to the
    nearest stream pixel and records that stream pixel's row and column
    indices. DEM nodata areas are preserved in all output bands.

    Parameters
    ----------
    dem : Path
        Path to the Digital Elevation Model (DEM) GeoTIFF. Used for spatial
        reference and nodata masking. DEM and streams rasters must be aligned
        (same CRS, resolution, and extent).
    streams : Path
        Path to the streams raster GeoTIFF. Non-zero values are treated as
        stream pixels. Typically generated by tools like WhiteboxTools
        'extract_streams'. Must be aligned with the DEM.
    output : Path
        Path for the output 3-band GeoTIFF file.

    Returns
    -------
    None
        Writes a 3-band GeoTIFF to disk with the following bands:
        - Band 1: Distance to nearest stream (float32, in map units/meters)
        - Band 2: Row index of nearest stream pixel (float32)
        - Band 3: Column index of nearest stream pixel (float32)
    """

    with rasterio.open(dem) as src:
        dem_profile = src.profile.copy()
        dem_data = src.read(1)
        dem_nodata = src.nodata
        nodata_mask = dem_data == dem_nodata

    with rasterio.open(streams) as src:
        streams_data = src.read(1)
        stream_mask = streams_data > 0
        transform = src.transform

    if not stream_mask.any():
        raise ValueError("No stream pixels found!")

    # Get pixel spacing in map units for accurate distance calculation.
    pixel_height = abs(transform.e)
    pixel_width = abs(transform.a)

    # Compute distances and indices of nearest stream pixel.
    distances, indices = distance_transform_edt(
        ~stream_mask,
        sampling=(pixel_height, pixel_width),
        return_distances=True,
        return_indices=True
        )

    # indices shape: (2, rows, cols)
    # indices[0] = row index of nearest stream pixel
    # indices[1] = col index of nearest stream pixel
    nearest_rows = indices[0]
    nearest_cols = indices[1]

    # Set nodata value where dem is null.
    distances[nodata_mask] = dem_nodata
    nearest_rows[nodata_mask] = dem_nodata
    nearest_cols[nodata_mask] = dem_nodata

    # Write output raster with 3 bands (all float32):
    # Band 1: Distance to nearest stream pixel in meters
    # Band 2: Row index of nearest stream pixel
    # Band 3: Column index of nearest stream pixel
    out_profile = dem_profile.copy()
    out_profile.update(
        dtype=rasterio.float32,
        count=3,
        compress='deflate'
        )

    with rasterio.open(output, 'w', **out_profile) as dst:
        dst.write(distances.astype(np.float32), 1)
        dst.write(nearest_rows.astype(np.float32), 2)
        dst.write(nearest_cols.astype(np.float32), 3)

        # Add band descriptions
        dst.set_band_description(1, 'distance_to_stream_meters')
        dst.set_band_description(2, 'nearest_stream_row')
        dst.set_band_description(3, 'nearest_stream_col')


def height_above_stream(output: Path, dem: Path, streams: Path):
    # Read DEM data and metadata.
    with rasterio.open(dem) as src:
        dem_data = src.read(1).astype('float32')
        meta = src.meta.copy()
        nodata = src.nodata

    # Replace nodata by nan.
    dem_data[dem_data == nodata] = np.nan

    # Read streams (0 = no stream, >0 = stream).
    with rasterio.open(streams) as src:
        streams_data = src.read(1)

    # Create binary stream mask (1 = stream, 0 = non-stream).
    stream_mask = streams_data > 0

    # Get elevation of nearest stream for each pixel
    indices = distance_transform_edt(
        ~stream_mask,
        return_distances=False,
        return_indices=True)

    rows = indices[0]
    cols = indices[1]

    nearest_stream_elevation = dem_data[rows, cols]

    # Calculate elevation above nearest stream
    elevation_above_stream = dem_data - nearest_stream_elevation

    # Fill nan value with nodata.
    elevation_above_stream[np.isnan(elevation_above_stream)] = nodata

    # Save elevation above stream
    meta.update(dtype='float32')
    with rasterio.open(output, 'w', **meta) as dst:
        dst.write(elevation_above_stream.astype('float32'), 1)
